import type { Recipe } from "@/types/recipe"

export const sampleRecipes: Recipe[] = [
  {
    id: "1",
    title: "Classic Spaghetti Carbonara",
    description: "A traditional Italian pasta dish with eggs, cheese, pancetta, and black pepper.",
    ingredients: [
      "350g spaghetti",
      "150g pancetta or guanciale, diced",
      "3 large eggs",
      "50g pecorino romano cheese, grated",
      "50g parmesan cheese, grated",
      "Freshly ground black pepper",
      "Salt to taste",
    ],
    instructions: [
      "Bring a large pot of salted water to boil and cook spaghetti according to package instructions.",
      "While pasta cooks, heat a large skillet over medium heat and cook the pancetta until crispy.",
      "In a bowl, whisk together eggs, grated cheeses, and black pepper.",
      "Drain pasta, reserving 1/2 cup of pasta water.",
      "Working quickly, add hot pasta to the skillet with pancetta, remove from heat.",
      "Add the egg and cheese mixture, stirring constantly. Add pasta water as needed to create a creamy sauce.",
      "Serve immediately with extra grated cheese and black pepper.",
    ],
    category: "Italian",
    prepTime: 10,
    cookTime: 15,
    servings: 4,
    isFavorite: false,
    image: "/placeholder.svg?height=300&width=400",
    createdAt: 1647984000000,
    updatedAt: 1647984000000,
  },
  {
    id: "2",
    title: "Chicken Tikka Masala",
    description: "Grilled chunks of chicken enveloped in a creamy spiced tomato sauce.",
    ingredients: [
      "800g boneless chicken thighs, cut into chunks",
      "2 cups plain yogurt",
      "3 tbsp lemon juice",
      "4 tsp ground cumin",
      "4 tsp ground coriander",
      "2 tsp garam masala",
      "2 tsp paprika",
      "2 tsp turmeric",
      "2 onions, finely chopped",
      "4 garlic cloves, minced",
      "2 tbsp ginger, grated",
      "800g canned tomatoes",
      "300ml heavy cream",
      "Fresh cilantro for garnish",
    ],
    instructions: [
      "Combine yogurt, lemon juice, and half the spices in a bowl. Add chicken and marinate for at least 1 hour.",
      "Preheat oven to 400°F (200°C). Place chicken on a baking sheet and cook for 15 minutes.",
      "Heat oil in a large pan. Add onions and cook until soft.",
      "Add garlic and ginger, cook for 2 minutes. Add remaining spices and cook for 1 minute.",
      "Add tomatoes and simmer for 15 minutes. Add cream and simmer for 5 more minutes.",
      "Add the cooked chicken and simmer for 5-10 minutes.",
      "Garnish with cilantro and serve with rice or naan bread.",
    ],
    category: "Indian",
    prepTime: 20,
    cookTime: 40,
    servings: 6,
    isFavorite: true,
    image: "/placeholder.svg?height=300&width=400",
    createdAt: 1648070400000,
    updatedAt: 1648070400000,
  },
  {
    id: "3",
    title: "Avocado Toast with Poached Egg",
    description: "A simple, nutritious breakfast that's ready in minutes.",
    ingredients: [
      "2 slices of sourdough bread",
      "1 ripe avocado",
      "2 eggs",
      "1 tbsp white vinegar",
      "Salt and pepper to taste",
      "Red pepper flakes (optional)",
      "Fresh herbs like cilantro or chives (optional)",
    ],
    instructions: [
      "Toast the bread slices until golden and crisp.",
      "Cut the avocado in half, remove the pit, and scoop the flesh into a bowl.",
      "Mash the avocado with a fork, season with salt and pepper.",
      "Bring a pot of water to a gentle simmer, add vinegar.",
      "Crack each egg into a small cup, then gently slide into the simmering water.",
      "Poach for 3-4 minutes until whites are set but yolks are still runny.",
      "Spread mashed avocado on toast, top with poached eggs.",
      "Season with salt, pepper, red pepper flakes, and herbs if desired.",
    ],
    category: "Breakfast",
    prepTime: 5,
    cookTime: 5,
    servings: 1,
    isFavorite: false,
    image: "/placeholder.svg?height=300&width=400",
    createdAt: 1648156800000,
    updatedAt: 1648156800000,
  },
  {
    id: "4",
    title: "Classic Beef Burger",
    description: "Juicy homemade beef burgers with all the fixings.",
    ingredients: [
      "500g ground beef (80% lean)",
      "1 small onion, finely diced",
      "2 garlic cloves, minced",
      "1 tbsp Worcestershire sauce",
      "1 egg",
      "Salt and pepper to taste",
      "4 burger buns",
      "Lettuce, tomato, onion for serving",
      "Cheese slices (optional)",
      "Condiments of choice",
    ],
    instructions: [
      "In a large bowl, combine ground beef, onion, garlic, Worcestershire sauce, egg, salt, and pepper.",
      "Mix gently with your hands until just combined. Don't overmix.",
      "Divide the mixture into 4 equal portions and shape into patties about 1/2 inch thick.",
      "Make a slight depression in the center of each patty to prevent it from puffing up during cooking.",
      "Heat a grill or skillet over medium-high heat. Cook patties for 4-5 minutes per side for medium doneness.",
      "If adding cheese, place a slice on each patty during the last minute of cooking.",
      "Toast the buns lightly if desired.",
      "Assemble burgers with your favorite toppings and condiments.",
    ],
    category: "American",
    prepTime: 15,
    cookTime: 10,
    servings: 4,
    isFavorite: true,
    image: "/placeholder.svg?height=300&width=400",
    createdAt: 1648243200000,
    updatedAt: 1648243200000,
  },
  {
    id: "5",
    title: "Vegetable Stir Fry",
    description: "A quick and healthy vegetable stir fry with a savory sauce.",
    ingredients: [
      "2 tbsp vegetable oil",
      "2 garlic cloves, minced",
      "1 tbsp ginger, grated",
      "1 bell pepper, sliced",
      "1 carrot, julienned",
      "1 cup broccoli florets",
      "1 cup snap peas",
      "1 cup mushrooms, sliced",
      "3 tbsp soy sauce",
      "1 tbsp oyster sauce",
      "1 tsp sesame oil",
      "1 tsp cornstarch mixed with 2 tbsp water",
      "Sesame seeds for garnish",
    ],
    instructions: [
      "Heat oil in a wok or large skillet over high heat.",
      "Add garlic and ginger, stir for 30 seconds until fragrant.",
      "Add vegetables in order of cooking time: carrots first, then bell pepper, broccoli, snap peas, and mushrooms last.",
      "Stir-fry for 4-5 minutes until vegetables are crisp-tender.",
      "In a small bowl, mix soy sauce, oyster sauce, sesame oil, and cornstarch slurry.",
      "Pour sauce over vegetables and stir to coat. Cook for 1-2 minutes until sauce thickens.",
      "Garnish with sesame seeds and serve over rice or noodles.",
    ],
    category: "Asian",
    prepTime: 15,
    cookTime: 10,
    servings: 4,
    isFavorite: false,
    image: "/placeholder.svg?height=300&width=400",
    createdAt: 1648329600000,
    updatedAt: 1648329600000,
  },
]

